"""
Unit Tests for Service Layer (Inventory, Analytics, Prediction).
Tests products additions/updates, logical deactivations, bulk CSV imports,
delivery entries, weekly stock calculations, reports and prediction triggers.
"""

import os
import pytest
import json
import pandas as pd
from datetime import datetime

from backend.database.db_manager import DBManager
from backend.models.entities import Product, DailyEntry, StockMovement
from backend.services.inventory_service import InventoryService
from backend.services.analytics_service import AnalyticsService
from backend.services.prediction_service import PredictionService
from backend.utils.validators import ValidationError, DuplicateProductError, validate_required_fields, validate_date_format
from backend.utils.helpers import compute_data_hash, get_weeks_between, get_season

@pytest.fixture
def test_db(tmp_path):
    db_file = tmp_path / "service_test.db"
    return DBManager(str(db_file))

def test_inventory_service_product_crud(test_db):
    """Tests product ADD, UPDATE, and DEACTIVATE services."""
    inv_svc = InventoryService(test_db)
    
    p = Product(sku="SKU-T1", name="Bread", category="Bakery", current_stock=20, unit_cost=2.5, reorder_point=5)
    
    # 1. Add Product
    p_id = inv_svc.add_product(p)
    assert p_id > 0
    
    # Check duplicate SKU
    p_dup = Product(sku="SKU-T1", name="Wheat Bread", category="Bakery", current_stock=10, unit_cost=3.0)
    with pytest.raises(DuplicateProductError):
        inv_svc.add_product(p_dup)
        
    # Check duplicate Name
    p_name_dup = Product(sku="SKU-T2", name="Bread", category="Bakery", current_stock=10, unit_cost=3.0)
    with pytest.raises(DuplicateProductError):
        inv_svc.add_product(p_name_dup)
        
    # 2. Update Product
    p_update = Product(id=p_id, sku="SKU-T1", name="Whole Wheat Bread", category="Bakery", current_stock=22, unit_cost=2.8, reorder_point=5)
    assert inv_svc.update_product(p_update)
    
    fetched = test_db.get_product(p_id)
    assert fetched.name == "Whole Wheat Bread"
    assert fetched.current_stock == 22
    
    # 3. Deactivate Product (logical)
    assert inv_svc.deactivate_product(p_id)
    assert not inv_svc.is_active("SKU-T1")
    
    # Active products list should be empty
    active_prods = inv_svc.list_active_products()
    assert len(active_prods) == 0

def test_weekly_stock_submission_and_sales_calculation(test_db):
    """
    Tests weekly stock submissions:
    - Previous stock + deliveries - remaining_stock = sales
    - Clamp negative sales at zero
    """
    inv_svc = InventoryService(test_db)
    
    # 1. Add product with 10 starting stock
    p = Product(sku="MILK-01", name="Milk 1L", category="Dairy", current_stock=10, unit_cost=1.5, reorder_point=5)
    p_id = inv_svc.add_product(p)
    
    # 2. Record delivery of 15 units during the week (current stock should become 25)
    inv_svc.record_delivery(sku="MILK-01", quantity=15, supplier_name="Dairy Farm", cost_per_unit=1.5, movement_date="2026-07-05")
    
    p_after_delivery = test_db.get_product(p_id)
    assert p_after_delivery.current_stock == 25
    
    # 3. Submit weekly remaining stock as 8 units
    # Deliveries = 15. Previous Stock = 25 - 15 = 10.
    # Weekly Sales = Previous Stock + Deliveries - remaining = 10 + 15 - 8 = 17 units.
    # Stock level should update to 8.
    res = inv_svc.submit_weekly_stock(sku="MILK-01", remaining_stock=8, entry_date="2026-07-11")
    
    assert res["weekly_sales"] == 17
    assert res["previous_stock"] == 10
    assert res["deliveries"] == 15
    assert res["current_stock"] == 8
    
    p_after_submit = test_db.get_product(p_id)
    assert p_after_submit.current_stock == 8
    
    # Verify sales recorded in daily_entries table
    entries = test_db.get_daily_entries_for_product(p_id)
    assert len(entries) == 1
    assert entries[0].units_sold == 17
    assert entries[0].units_wasted == 0

def test_analytics_service_queries(test_db):
    """Tests the analytics reports generated by AnalyticsService."""
    inv_svc = InventoryService(test_db)
    anal_svc = AnalyticsService(test_db)
    
    # Add products
    p1_id = inv_svc.add_product(Product(sku="A-1", name="Apple", category="Produce", current_stock=20, unit_cost=1.0, reorder_point=5))
    p2_id = inv_svc.add_product(Product(sku="B-2", name="Banana", category="Produce", current_stock=5, unit_cost=0.5, reorder_point=10))
    
    # Record weekly stock (which logs sales daily_entries)
    inv_svc.submit_weekly_stock("A-1", remaining_stock=10, entry_date="2026-07-11") # Sales = 10
    inv_svc.submit_weekly_stock("B-2", remaining_stock=2, entry_date="2026-07-11")  # Sales = 3
    
    # 1. Top Selling
    top = anal_svc.get_top_selling_products()
    assert len(top) == 2
    assert top[0]["sku"] == "A-1" # Apple sold 10, Banana sold 3
    
    # 2. Below Reorder Point
    below = anal_svc.get_products_below_reorder_point()
    assert len(below) == 1
    assert below[0]["sku"] == "B-2" # stock=2, reorder=10
    
    # 3. Inventory Turnover
    turnover = anal_svc.get_inventory_turnover()
    # Apple: COGS = 10 sold * 1.0 = 10.0. Banana: COGS = 3 sold * 0.5 = 1.5. Total COGS = 11.5
    # Stock Value = Apple (10 stock * 1.0 = 10.0) + Banana (2 stock * 0.5 = 1.0) = 11.0
    # Turnover ratio = 11.5 / 11.0 = 1.05
    assert turnover["cogs"] == 11.5
    assert turnover["inventory_turnover_ratio"] == pytest.approx(1.05)
    
    # 4. Other analytical queries
    fast = anal_svc.get_fastest_moving_inventory()
    assert len(fast) == 2
    slow = anal_svc.get_slow_moving_inventory()
    assert len(slow) == 2
    m_sum = anal_svc.get_monthly_summaries()
    assert len(m_sum) == 1
    c_sum = anal_svc.get_category_summaries()
    assert len(c_sum) == 1
    
    # Delivery and sales history queries
    assert len(anal_svc.get_delivery_history()) == 0
    inv_svc.record_delivery("A-1", 10, "Supplier", 1.0)
    assert len(anal_svc.get_delivery_history()) == 1
    assert len(anal_svc.get_delivery_history(product_id=p1_id)) == 1
    
    assert len(anal_svc.get_historical_sales()) == 1
    assert len(anal_svc.get_historical_sales(product_id=p1_id)) == 1
    assert len(anal_svc.get_forecast_trends()) == 0

def test_prediction_service_pipeline(test_db):
    """Tests execution of the ML pipeline coordinator from PredictionService."""
    inv_svc = InventoryService(test_db)
    pred_svc = PredictionService(test_db)
    
    # Test 1: No active products
    assert len(pred_svc.run_predictions()) == 0
    
    # Test 2: Product exists but no sales history
    inv_svc.add_product(Product(sku="A", name="Apple", category="Produce", current_stock=20, unit_cost=1.0))
    assert len(pred_svc.run_predictions()) == 0
    
    # Setup some historical sales to satisfy ML training requirements (>=4 weeks of sales)
    # We log sales for past 5 weeks
    dates = ["2026-06-01", "2026-06-08", "2026-06-15", "2026-06-22", "2026-06-29"]
    for d in dates:
        inv_svc.submit_weekly_stock("A", remaining_stock=15, entry_date=d)
        
    results = pred_svc.run_predictions()
    assert len(results) == 1
    assert results[0].sku == "A"
    assert results[0].forecast_7d >= 0.0
    assert results[0].stock_status in ["Critical", "Low", "Healthy", "Overstock"]
    assert results[0].eoq >= 0
    assert len(results[0].explanations) > 0
    
    # Verify forecast trends can now be fetched since prediction service has run once
    anal_svc = AnalyticsService(test_db)
    trends = anal_svc.get_forecast_trends()
    assert len(trends) == 1
    assert trends[0]["sku"] == "A"
    
    # Test 3: Run pipeline with DataFrame directly
    df = pd.DataFrame({
        "sku": ["A", "A"],
        "name": ["Apple", "Apple"],
        "category": ["Produce", "Produce"],
        "sales_volume": [2, 3],
        "date": ["2026-07-01", "2026-07-02"],
        "product_id": [1, 1],
        "current_stock": [20, 20],
        "unit_cost": [1.0, 1.0],
        "reorder_point": [10, 10]
    })
    df_results = pred_svc.run_pipeline_with_dataframe(df)
    assert len(df_results) == 1
    
    # Check pipeline history recorded in database
    history = pred_svc.get_prediction_history()
    assert len(history) == 1
    assert history[0]["success"] == 1

def test_bulk_csv_import(test_db, tmp_path):
    """Tests bulk CSV import functionality and column checking."""
    inv_svc = InventoryService(test_db)
    
    # Write a valid CSV
    csv_file = tmp_path / "import_test.csv"
    data = {
        "sku": ["CSV-1", "CSV-2"],
        "name": ["Mango", "Orange"],
        "category": ["Fruit", "Fruit"],
        "current_stock": [15, 20],
        "unit_cost": [2.5, 1.8],
        "reorder_point": [5, 8]
    }
    pd.DataFrame(data).to_csv(csv_file, index=False)
    
    res = inv_svc.bulk_csv_import(str(csv_file))
    assert res["inserted"] == 2
    assert res["updated"] == 0
    
    # Attempting to import same file again should update
    res2 = inv_svc.bulk_csv_import(str(csv_file))
    assert res2["inserted"] == 0
    assert res2["updated"] == 2

    # Malformed CSV test
    bad_csv = tmp_path / "bad.csv"
    pd.DataFrame({"invalid": [1, 2]}).to_csv(bad_csv, index=False)
    with pytest.raises(ValidationError):
        inv_svc.bulk_csv_import(str(bad_csv))

def test_helpers_and_validators():
    """Tests utility functions and standard input validation checks."""
    # Hashing
    df = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
    h1 = compute_data_hash(df)
    h2 = compute_data_hash(df)
    assert h1 == h2
    assert len(h1) == 64
    
    # Weeks between
    weeks = get_weeks_between("2026-07-01", "2026-07-15")
    assert weeks == 2.0
    
    # Season
    assert get_season(4) == 1 # Spring
    assert get_season(7) == 2 # Summer
    
    # Validators
    with pytest.raises(ValidationError):
        validate_required_fields({"name": ""}, ["name"])
    with pytest.raises(ValidationError):
        validate_date_format("bad-date", "date")

def test_inventory_service_exceptions(test_db, tmp_path):
    """Tests that InventoryService methods raise appropriate ValidationErrors for edge cases."""
    inv_svc = InventoryService(test_db)
    
    # Non-existent file bulk import
    with pytest.raises(ValidationError, match="CSV file not found"):
        inv_svc.bulk_csv_import("non_existent_file.csv")
        
    # Non-existent product operations
    with pytest.raises(ValidationError, match="does not exist"):
        inv_svc.deactivate_product(999)
        
    with pytest.raises(ValidationError, match="does not exist"):
        inv_svc.update_product(Product(id=999, sku="SKU", name="Name"))
        
    with pytest.raises(ValidationError, match="does not exist"):
        inv_svc.record_delivery(sku="NONEXISTENT", quantity=10)
        
    with pytest.raises(ValidationError, match="does not exist"):
        inv_svc.submit_weekly_stock(sku="NONEXISTENT", remaining_stock=5, entry_date="2026-07-11")
        
    # Bulk import duplicate product name
    inv_svc.add_product(Product(sku="SKU-REAL", name="Real Product"))
    
    csv_file = tmp_path / "dup_name.csv"
    data = {
        "sku": ["SKU-NEW"],
        "name": ["Real Product"],  # Matches existing name but has different SKU
        "category": ["Fruit"],
        "current_stock": [10],
        "unit_cost": [2.5]
    }
    pd.DataFrame(data).to_csv(csv_file, index=False)
    
    with pytest.raises(DuplicateProductError):
        inv_svc.bulk_csv_import(str(csv_file))
